name: ebookingdoc
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # SDK-only packages
  flutter_localizations:
    sdk: flutter

  go_router: ^15.1.2
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  shared_preferences: ^2.3.3
  intl: ^0.19.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.16
  flutter_dotenv: ^5.2.1
  image_picker: ^1.1.2
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1
  dio: ^5.8.0+1

  webview_flutter: ^4.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:

  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/.env
